[package]
name = "lib_treblecross"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Treblecross solver library using negamax"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
